# netlify.toml

[build]
  # Substitua 'sua_instrucao_de_build_aqui' pelo comando que você usa para construir seu site
  # Ex: command = "npm run build" ou "yarn build" ou deixe vazio se não houver build formal
  command = ""
  # Substitua 'seu_diretorio_de_deploy' pelo diretório que o Netlify deve servir
  # Ex: publish = "dist" ou "build" ou "." se a raiz for o diretório de deploy
  publish = "."

[functions]
  # Este é o diretório onde suas funções Netlify estarão
  # Certifique-se de que este diretório exista
  directory = "netlify/functions"

# Você pode adicionar outras configurações aqui, se necessário
